version: 2
jobs:
  build:
    working_directory: ~/python-scrapbox
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout:
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv run nosetests